openapi: 3.0.0

info:
  title: Unisave Watchdog
  description: Watchdog API documentation
  # What version of the watchdog this yaml file describes.
  # May differ from the version in the GitHub repository,
  # depending on how this file is modified.
  version: 0.6.3

externalDocs:
  description: More documentation available on Github
  url: 'https://github.com/unisave-cloud/watchdog'
  
paths:
  /:
    post:
      summary: "Execution request"
      description: "Fulfills an execution request"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
            examples:
              "Facet Call":
                value: |
                  {
                    "method": "facet-call",
                    "methodParameters": {
                      "facetName": "SomeFacet",
                      "methodName": "MyMethod",
                      "arguments": ["first", "second", 42],
                      "sessionId": "DpVNxtkzCBqDx-o="
                    },
                    "env": "FOO=bar\nBAZ=asd\n"
                  }
      responses:
        "200":
          description: "Execution response"
          content:
            application/json:
              examples:
                "Success":
                  value: |
                    {
                      "result": "ok",
                      "returned": null,
                      "special": {
                        "sessionId": "DpVNxtkzCBqDx-o="
                      }
                    }
                "Exception":
                  value: |
                    {
                      "result": "exception",
                      "exception": {
                        "ClassName": "System.Exception",
                        "Message": "Hello world!",
                        "StackTraceString": "   at UnisaveWorker"
                      },
                      "special": {
                        "sessionId": "DpVNxtkzCBqDx-o="
                      }
                    }
        "429":
          description: "Worker queue is full"
          content:
            text/plain:
              example: "Worker queue is full\n"
        "500":
          description: "Worker couldn't fulfill the request"
          content:
            text/plain:
              example: "Worker is unhealthy\n"
  /_/health:
    get:
      summary: "Healthcheck"
      responses:
        "200":
          description: "Healthy"
          content:
            text/plain:
              example: "OK\n"
        "503":
          description: "Not healthy"
          content:
            text/plain:
              example: "Service Unavailable\n"
  /metrics:
    get:
      summary: "Prometheus metrics"
      responses:
        "200":
          description: "Prometheus text format, see: https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-example"
          content:
            "text/plain; version=0.0.4":
              example: |
                # HELP worker_requests_total The total number of execution requests.
                # TYPE worker_requests_total counter
                worker_requests_total 42
  /status:
    get:
      summary: "Worker status description"
      description: |
        Should provide an overview of the worker state. **Not implemented.**
      responses:
        "200":
          description: "OK"
